apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6gcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6gcl
    app.kubernetes.io/part-of: tkrw-pr714-0075-0073-app
  name: devfile-sample-6gcl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6gcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6gcl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0073-tenant/tkrw-pr714-0075-0073-app/devfile-sample-6gcl@sha256:239ddffce2a35fc5bc4d587e47ee52fc9149dbc0149218942a0fb48ec7e6a0a7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
